version: 2.1

orbs:
  python: circleci/python@0.3.8

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: ./manage.py main
          name: main

workflows:
  main:
    jobs:
      - build-and-test
